# config/packages/liip_imagine.yaml
liip_imagine:
  resolvers:
    default:
      web_path: ~
  loaders:
    default:
      filesystem:
        data_root: "/" # <-- This setting
  # Configuration par défaut
  driver: "gd" # ou "imagick" si vous préférez utiliser Imagick
  filter_sets:
    cache: ~
    chat_image:
      quality: 75
      filters:
        thumbnail: { size: [1080, 1080], mode: outbound }
    profile_image:
      quality: 75
      filters:
        thumbnail: { size: [100, 100], mode: outbound }
